"""
Pytest configuration for the physics validation audit suite (Phase 1).

The audit suite is deselected from the default test run (pyproject.toml
addopts contains `-m 'not audit'`). Invoke it explicitly with:

    docker compose run --rm test pytest tests/audit/ -v -m audit

Each test writes a CSV table to `/tmp/audit/<case>.csv` and a markdown
fragment to `/tmp/audit/<case>.md`. After the session finishes, the
fragments are aggregated into `docs/PHYSICS_AUDIT.md` so a single PR
artifact captures the audit results.
"""
from __future__ import annotations

from pathlib import Path

import pytest

AUDIT_DIR = Path("/tmp/audit")
PHYSICS_AUDIT_MD = Path(__file__).resolve().parents[2] / "docs" / "PHYSICS_AUDIT.md"


@pytest.fixture(scope="session", autouse=True)
def _audit_output_dir():
    """Ensure /tmp/audit/ exists before any audit test runs."""
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    yield AUDIT_DIR


def pytest_sessionfinish(session, exitstatus):
    """Aggregate per-case markdown fragments into docs/PHYSICS_AUDIT.md.

    Only runs if the user explicitly requested the audit marker
    (`-m audit`). Otherwise the audit tests were not collected and there
    are no fragments to assemble.
    """
    marker_expr = session.config.getoption("-m") or ""
    if "audit" not in marker_expr:
        return

    fragments = sorted(AUDIT_DIR.glob("*.md"))
    if not fragments:
        return

    header = (
        "# Physics validation audit\n\n"
        "This document is generated by the audit suite "
        "(`tests/audit/`, run with `pytest -m audit`). Each section "
        "below corresponds to one cross-runner consistency case "
        "(Phase 1 of the validation suite, see PLAN.md). The CSV "
        "tables referenced live in `/tmp/audit/` and are not committed.\n\n"
        "Regenerate this file with:\n\n"
        "    docker compose run --rm test pytest tests/audit/ -v -m audit\n\n"
        "---\n\n"
    )

    parts = [header]
    for frag in fragments:
        parts.append(frag.read_text())
        parts.append("\n\n---\n\n")

    # Optional manual notes appended at the end of the regenerated
    # document. The notes file is committed with the PR that records
    # the audit findings; the per-case fragments above are the
    # mechanical numerical record, while the notes are the narrative
    # summary, classification, deferred issues, and recommendation.
    notes_path = Path(__file__).resolve().parent / "notes_phase1.md"
    if notes_path.exists():
        parts.append(notes_path.read_text())
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    PHYSICS_AUDIT_MD.parent.mkdir(parents=True, exist_ok=True)
    PHYSICS_AUDIT_MD.write_text("".join(parts))
